export type Styles = {
  app: string;
  'nav-icon': string;
  'nav-icon-right': string;
  'nav-header': string;
  'nav-title': string;
  'nav-title-content': string;
  'main-title': string;
  'main-component': string;
  'main-wrap': string;
  'main-content': string;
  'main-content-row': string;
  'main-content-input': string;
  'main-button-wrap': string;
  'main-button': string;
  'signUp-popup': string;
  'popup-header': string;
  'popup-title': string;
  'popup-body': string;
  'popup-content-list': string;
  'popup-content-item': string;
  'popup-content-item-title': string;
  'popup-content-item-input': string;
  'popup-footer': string;
  'popup-button': string;
  'side-view-component': string;
  'side-view-chatting-list': string;
  'side-view-chatting-item': string;
  'side-view-chatting-wrap': string;
  'side-view-chatting-input': string;
  'side-view-chatting-button': string;
  'side-view-chatting-item-header': string;
  'side-view-chatting-item-content': string;
  'hashtag-wrap': string;
  'hashtag-content': string;
  'hashtag-content-title': string;
  'hashtag-content-title-wrap': string;
  'hashtag-content-title-sport': string;
  'hashtag-content-title-economy': string;
  'hashtag-content-title-science': string;
  'hashtag-content-title-entertainment': string;
  'hashtag-content-count': string;
  'hashtag-content-item': string;
  'hashtag-filter-header': string;
  'hashtag-filter-header-combobox': string;
  'hashtag-filter-header-input': string;
};

export type ClassNames = keyof Styles;

declare const styles: Styles;

export default styles;
